application: collab-video-xiaolong
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /resource
  static_dir: resource
- url: /.*
  script: main.application
